polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'

urlpatterns = [
    # /polls/
    path('', views.index, name='index'),    
    path('articles/', views.articles, name='articles'),
    path('articles/<str:topic_genre>/', views.articles_genre, name='articles_genre'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('profile/', views.profile, name='profile'),
    # /polls/5/results
    # path('<int:question_id>/results/', views.results, name='results'),
    # /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

choices = (('IT(その他)','IT(その他)'),('Accountant', 'Accountant'),('Everyday', 'Everyday'), ('Eye', 'Eye'), ('ハリネズミ', 'ハリネズミ'), ('Python(Django)','Python(Django)'), ('Swift', 'Swift'))

class Topic(models.Model):

    genre= models.CharField(max_length=100, default='Everyday', choices=choices)
    title= models.CharField(max_length=100, default='')
    topic_text = models.TextField(default='')
    pub_date = models.DateTimeField('date published')
    nice = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from .models import Topic


def index(request):
    topic_list = Topic.objects.order_by('-pub_date')[:5]
    context = {
        'topic_list': topic_list,
    }
    # template = loader.get_template('polls/index.html')
    # return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', context)


def detail(request, topic_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question dows not exist.")
    if request.method == "POST":
        nice = request.POST['nice']
        print('押されました！')

    topic = get_object_or_404(Topic, pk=topic_id)

    ranking_list = Topic.objects.all().order_by('-nice')[:5]
    rank = 1
    for ranking_topic in ranking_list:
        ranking_topic.title = "第" + str(rank) + "位：" + ranking_topic.title
        rank += 1
    
    genre_list = Topic.objects.values_list('genre', flat=True)
    
    context = {
        'topic': topic,
        'ranking_list': ranking_list,
        'genre_list': set(genre_list)
    }

    return render(request, 'polls/detail.html', context)

def articles(request):
    if request.method == "POST":
        search_word = request.POST['search_word']
        topic_list = Topic.objects.filter(Q(title__contains=search_word) | Q(topic_text__contains=search_word)).distinct()
        # topic_list = Topic.objects.all().order_by('-pub_date')
    else:
        topic_list = Topic.objects.all().order_by('-pub_date')

    for topic in topic_list:
        if len(topic.topic_text) > 100:
            topic.topic_text = topic.topic_text[:100] + '.'*5
    
    ranking_list = Topic.objects.all().order_by('-nice')[:5]
    rank = 1
    for topic in ranking_list:
        topic.title = "第" + str(rank) + "位：" + topic.title
        rank += 1
    
    for topic in topic_list:
        print(topic, topic.id)
    
    genre_list = Topic.objects.values_list('genre', flat=True)
        
    context = {
        'topic_list': topic_list,
        'ranking_list': ranking_list,
        'genre_list': set(genre_list)
    }

    return render(request, 'polls/articles.html', context)

def articles_genre(request, topic_genre):
    # メインのトピックリスト 
    topic_list = Topic.objects.filter(genre=topic_genre).order_by('-pub_date')
    for topic in topic_list:
        if len(topic.topic_text) > 100:
            topic.topic_text = topic.topic_text[:100] + '.'*5
    
    # いいねランキングのトピックリスト
    ranking_list = Topic.objects.all().order_by('-nice')[:5]
    rank = 1
    for topic in ranking_list:
        topic.title = "第" + str(rank) + "位：" + topic.title 
        rank += 1
        

    topic_gen = topic_genre

    genre_list = Topic.objects.values_list('genre', flat=True)

        
    context = {
        'topic_list': topic_list,
        'ranking_list': ranking_list,
        'topic_gen': topic_genre,
        'genre_list': set(genre_list)
    }
    return render(request, 'polls/articles.html', context)


def profile(request):
    
    topic_list = Topic.objects.all().order_by('-pub_date')
    for topic in topic_list:
        if len(topic.topic_text) > 100:
            topic.topic_text = topic.topic_text[:100] + '.'*5
    
    ranking_list = Topic.objects.all().order_by('-nice')[:5]
    rank = 1
    for topic in ranking_list:
        topic.title = "第" + str(rank) + "位：" + topic.title + " "
    
    profile_text = "IT業界の片隅にいるネコです。昔はSEや会計士をやってました。好きなフレームワークはDjango、Reactです。たまにSwiftも書きます。"
    email = "1morimorimorita@gmail.com"

    genre_list = Topic.objects.values_list('genre', flat=True)

    
    context = {
        'profile_text': profile_text,
        'email': email,
        'topic_list': topic_list,
        'ranking_list': ranking_list,
        'genre_list': set(genre_list)

    }
    return render(request, 'polls/profile.html', context)

polls/templates/polls/articles.html
{% extends "./base/base.html" %}
<!DOCTYPE html>

{% block mainblock %}

        <main>
          <div class="search_form"> 
          <form action="{% url 'polls:articles' %}" method="post">
            {% csrf_token %}
              <label for="name"></label>
              <input type="text" id="search_word" name="search_word" placeholder="Search word...">
            <input class="input_button" type="submit" value="Search">
          </form>
        </div>

          {% if topic_gen %}
          <h1><a href="{% url 'polls:articles' %}">Articles</a> > 「{{ topic_gen }}」の記事一覧</h1>
          {% endif %}
          {% if topic_list %} {% for topic in topic_list %}
          <article>
            <h2 class="article-title">
              <a href="{% url 'polls:detail' topic.id %}">{{ topic.title }}</a>
            </h2>
            <ul class="meta">
              <li><a href="#">{{ topic.pub_date }}</a></li>
              <li><a href="{% url 'polls:articles_genre' topic.genre %}">{{ topic.genre }}</a></li>
              <li><a>{{ topic.nice }} いいね!</a></li>
            </ul>

            <p class="text">{{ topic.topic_text | linebreaksbr }}</p>

            <div class="readmore">
              <a href="{% url 'polls:detail' topic.id %}">READ MORE</a>
              
            </div>
            
          </article>
          {% endfor %} {% endif %}
        </main>
{% endblock %}

polls/templates/polls/articles_genre.html
{% extends "./base/base.html" %}
<!DOCTYPE html>

{% block mainblock %}
        <main>
          {% if topic_list %} {% for topic in topic_list %}
          <article>
            <h2 class="article-title">
              <a href="{% url 'polls:detail' topic.id %}">{{ topic.title }}</a>
            </h2>
            <ul class="meta">
              <li><a href="#">{{ topic.pub_date }}</a></li>
              <li><a href="#">{{ topic.genre }}</a></li>
            </ul>

            <p class="text">{{ topic.topic_text | linebreaksbr }}</p>

            <div class="readmore">
              <a href="{% url 'polls:detail' topic.id %}">READ MORE</a>
            </div>
          </article>
          {% endfor %} {% endif %}
        </main>
{% endblock %}

polls/templates/polls/base/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>MosCafe</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style_articles.css' %}"
    />

    <meta
      name="description"
      content="テキストテキストテキストテキストテキストテキストテキストテキス"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="{% static 'polls/img/saite_logo.png' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
      rel="stylesheet"
    />
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-2QWC1P8ZTE"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-2QWC1P8ZTE");
    </script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7884273815410740"
     crossorigin="anonymous"></script>
  </head>

  <body>
    <header id="header">
      <div class="yoko">
      <a href="{% url 'polls:profile' %}"
        ><img src="{% static 'polls/img/saite_logo.png' %}" alt="Profile"
      /></a>
      <h1>MosCafe</h1>
      <h3>
        危険を冒して前へ進もうとしない人、未知の世界を旅しようとしない人には、 人生は、ごくわずかな景色しか見せてくれないんだよ。    - シドニー・ポワチエ -
      </h3>
      </div>
 
      
      <nav id="navi">
        <ul class="wrapper">
          <li><a href="{% url 'polls:index' %}">HOME</a></li>
          <li class="menu__single"><a href="{% url 'polls:articles' %}">ARTICLES</a>
            {% comment %} <ul class="menu__second-level">
              <li><a href="#">Child Menu</a></li>
              <li><a href="#">Child Menu</a></li>
              <li><a href="#">Child Menu</a></li>
          </ul> {% endcomment %}
          </li>
          <li><a href="{% url 'polls:profile' %}">CONTACT</a></li>
        </ul>
      </nav>
      {% comment %} <ul class="menu">
        <li class="menu__single">
            <a href="#" class="init-bottom">Menu single</a>
            <ul class="menu__second-level">
                <li><a href="#">Child Menu</a></li>
                <li><a href="#">Child Menu</a></li>
                <li><a href="#">Child Menu</a></li>
            </ul>
        </li>
        <!-- 他グローバルナビメニュー省略 -->
    </ul> {% endcomment %}
    </header>

    <div id="pickup" class="wrapper"></div>

    <div class="other-body">
      <div id="container" class="wrapper">
        
          {% block mainblock %}
          {% endblock %}

        <aside id="sidebar">
          <section class="author">
            <img src="{% static 'polls/img/hati.jpeg' %}" />
            <h3 class="side-title">BARA</h3>
            <p class="profile">
              IT業界の隅に生息しているネコです。会計のことも少しわかります。
            </p>
          </section>

          <section class="genre">
            <h3 class="side-title">Genre</h3>

            <div class="genre_button_group">
              {% if genre_list %}
              {% for genre in genre_list %}
              <input class="genre_button" type="button" onClick="location.href='{% url 'polls:articles_genre' genre %}'" value="{{ genre }}">
            {% endfor %}
              {% endif %}
            </div>
          </section>



          <section class="ranking">
            <h3 class="side-title">Ranking</h3>
            {% if ranking_list %} {% for topic in ranking_list %}
            <article>
              <a href="{% url 'polls:detail' topic.id %}">
                <h3 class="article-title">
                  <span>{{ topic.title }}</span>
                  <div class="ranking_nice">
                  <h5>{{ topic.nice }}いいね</h5>
                  </div>
                </h3>
                
              </a>
            </article>
            {% endfor %} {% endif %}
          </section>

          <section class="archive">
            <h3 class="side-title">Archive</h3>
            <ul>
              <li><a href="#">2022年03月</a>(03)</li>
            </ul>
          </section>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7884273815410740"
     crossorigin="anonymous"></script>
<!-- third -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7884273815410740"
     data-ad-slot="2090311833"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
        </aside>
      </div>
    </div>

    <footer id="footer">
      <div class="content wrapper">
        <section class="item">
          <h3 class="footer-title">About</h3>
          <p>IT業界の隅に生息しているネコです。会計のことも少しわかります。</p>
          <ul class="about-list">
            <li><a href="{% url 'polls:profile' %}" class="arrow">プロフィール詳細</a></li>
            <li><a href="{% url 'polls:profile' %}" class="arrow">お問い合わせ</a></li>
          </ul>
        </section>

        <section class="item">
          <h3 class="footer-title">Menu</h3>
          <ul class="menu-list">
            <li><a href="{% url 'polls:index' %}">HOME</a></li>
            <li><a href="{% url 'polls:articles' %}">ARTICLES</a></li>
            <li><a href="{% url 'polls:profile' %}">CONTACT</a></li>
          </ul>
        </section>

        <section class="item">
          <h3 class="footer-title">Twitter</h3>
          <a
            class="twitter-timeline"
            data-height="315"
            href="https://twitter.com/TwitterJP?ref_src=twsrc%5Etfw"
            >Tweets by TwitterJP</a
          >
          <script async src="https://platform.twitter.com/widgets.js"></script>
        </section>
      </div>

      <p class="copyright">&copy; Travel & Blog</p>
    </footer>
  </body>
</html>

polls/templates/polls/detail.html
{% extends "./base/base.html" %}
{% load static %}

<!DOCTYPE html>

{% block mainblock %}
<main>
            {% if topic %}
            <h2>{{ topic.title }}</h2>
            <p>{{ topic.pub_date }}</p>
            <hr>
            {{ topic.topic_text | linebreaksbr }}
            <div class="text_nice">
                <h5>{{ topic.nice }}いいね</h5>

                <form action="{% url 'polls:detail' topic.id %}" method="post">
                    {% csrf_token %}
                <img src="{% static 'polls/img/crap.png' %}" >
                <input type="submit" name="nice" alt="nice!" value="">
                </form>
                
            </div>
            {% endif %}
</main>
{% endblock %}
            
  

polls/templates/polls/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>Profile</title>
    <link rel="shortcut icon" href="{% static 'polls/img/saite_logo.png' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style.css' %}"
    />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-2QWC1P8ZTE"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-2QWC1P8ZTE");
    </script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7884273815410740"
    crossorigin="anonymous"></script>
  </head>


  <body>
    <header id="header" class="wrapper">
      <h1 class="site-title">
        <a href="{% url 'polls:profile' %}"
          ><img src="{% static 'polls/img/profile_img.png' %}" alt="Profile"
        /></a>
      </h1>
      <nav>
        <ul>
          <li><a href="{% url 'polls:articles' %}">Articles</a></li>
          <li><a href="">Contact</a></li>
        </ul>
      </nav>
    </header>

    <main>
      <div id="mainvisual">
        <img
          src="{% static 'polls/img/library-3.jpeg' %}"
          alt="テキストテキストテキスト"
        />
      </div>

      <section id="about" class="wrapper">
        <h2 class="section-title">You've come all the way!</h2>
        <div class="content">
          <img
            src="{% static 'polls/img/hati.jpeg' %}"
            alt="サイトアイコン"
          />
          <div class="text">
            <h3 class="content-title">BARA</h3>
            <p>
              さまざまな分野で役に立ちそうな情報を発信するサイトです。<br />
              訪問してくれると喜びます　d(^_^o)<br />
            </p>
          </div>
        </div>
      </section>

      {% comment %} <section id="bicycle" class="wrapper">
        <h2 class="section-title">Bicycle</h2>
        <ul>
          <li>
            <img src="img/bicycle1.jpg" alt="テキストテキストテキスト" />
            <h3 class="content-title">タイトルタイトル</h3>
            <p>テキストテキストテキスト</p>
          </li>
          <li>
            <img src="img/bicycle2.jpg" alt="テキストテキストテキスト" />
            <h3 class="content-title">タイトルタイトル</h3>
            <p>テキストテキストテキスト</p>
          </li>
          <li>
            <img src="img/bicycle3.jpg" alt="テキストテキストテキスト" />
            <h3 class="content-title">タイトルタイトル</h3>
            <p>テキストテキストテキスト</p>
          </li>
        </ul>
      </section> {% endcomment %}

      {% comment %} <h2 class="home-title">Website...</h2>
      {% if topic_list %}
      <ul class="topic_list">
        {% for topic in topic_list %}
        <li>
          <a href="{% url 'polls:detail' topic.id %}">{{ topic.topic_text }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %} {% endif %}

      <h3>Click on the topic you are interested in.</h3> {% endcomment %}
    </main>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7884273815410740"
     crossorigin="anonymous"></script>
<!-- second -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7884273815410740"
     data-ad-slot="2653402703"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>


    <footer id="footer">
      <hr size="2">
      <p>&copy; 2022 Profile</p>
    </footer>
    
  </body>
</html>

polls/templates/polls/profile.html
{% extends "./base/base.html" %}
<!DOCTYPE html>

{% block mainblock %}
        <main>
          <article>
            <h2 class="article-title">
              <a href="">PLOFILE</a>
            </h2>
            <p class="text">{{ profile_text }}</p>
          </article>

          <article>
            <h2 class="article-title">
              <a href="">CONTACT</a>
            </h2>
            <p class="text">
              なにかお問い合わせがありましたら、こちらまでお願いします。
              → {{ email }}
            </p>
          </article>
        </main>
{% endblock %}